### ISSUE TITLE
[cetic/nifi] jq: error: Could not open file config.json: No such file or directory

### ISSUE THREAD

**Issue by drivard** [cetic/helm-nifi#103]
**Describe the bug**

I am trying to setup a first time nifi cluster using the helm chart. One of the objective is to use **OIDC** as the auth provider.

**Version of Helm and Kubernetes**:
Kubernetes 1.18.8
chart: 0.6.0 

**What happened**:

When I issue the helm install command line it passes, but it fails on initiating the nifi-0 pod. When I tail the logs of the init container named **cert-request** with the following command `k logs -f nifi-0 -c cert-request` I get a long list of logs with certain errors in there.

**What you expected to happen**:

I would have add a secured cluster that would have supported the OIDC auth provider.

**How to reproduce it** (as minimally and precisely as possible):

I issued the command line:

```
helm upgrade nifi ./helm-nifi/ \
  --install \
  --namespace nifi-test \
  --values values-test.yaml
```

Once I found the error I tried to remove the pvc(s) for `config-data-nifi-0` just to make sure to recreate the certs but it didn't changed the results.

**Anything else we need to know**:

State of the pods

```
NAME                       READY   STATUS                  RESTARTS   AGE
nifi-0                     0/5     Init:CrashLoopBackOff   7          19m
nifi-ca-5c99cb57d7-4kqrz   2/2     Running                 0          20m
nifi-zookeeper-0           2/2     Running                 0          39m
nifi-zookeeper-1           2/2     Running                 0          39m
nifi-zookeeper-2           2/2     Running                 0          39m
```

My stripped values file.
```
---
# Number of nifi nodes
replicaCount: 1

image:
  repository: apache/nifi
  tag: "1.12.1"
  pullPolicy: IfNotPresent

sts:
  # Parallel podManagementPolicy for faster bootstrap and teardown. Default is OrderedReady.
  podManagementPolicy: Parallel
  AntiAffinity: soft
  hostPort: null
  pod:
    annotations:
      security.alpha.kubernetes.io/sysctls: net.ipv4.ip_local_port_range=10000 65000
      #prometheus.io/scrape: "true"      
  serviceAccount:
    create: false
    #name: nifi

properties:
  # use externalSecure for when inbound SSL is provided by nginx-ingress or other external mechanism
  externalSecure: true
  isNode: true
  httpPort: 8080
  httpsPort: 8443
  clusterPort: 6007
  clusterSecure: true
  needClientAuth: false
  provenanceStorage: "8 GB"
  siteToSite:
    port: 10000
  authorizer: managed-authorizer
  # use properties.safetyValve to pass explicit 'key: value' pairs that overwrite other configuration
  safetyValve:
    #nifi.variable.registry.properties: "${NIFI_HOME}/example1.properties, ${NIFI_HOME}/example2.properties"
    nifi.web.http.network.interface.default: eth0
    # listen to loopback interface so "kubectl port-forward ..." works
    nifi.web.http.network.interface.lo: lo

# Nifi User Authentication
auth:
  oidc:
    enabled: true
    discoveryUrl: "<idp-url>"
    clientId: "<my_client>"
    clientSecret: "<my secret>"
    claimIdentifyingUser: email

# headless service
headless:
  type: ClusterIP
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

# ui service
service:
  type: ClusterIP
  httpPort: 8080
  httpsPort: 443
  annotations: {}
  # loadBalancerIP:
  ## Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24
  ## OIDC authentication requires "sticky" session on the LoadBalancer for JWT to work properly...but AWS doesn't like it on creation
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

# Amount of memory to give the NiFi java heap
jvmMemory: 2g

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true

# ca server details
# Setting this true would create a nifi-toolkit based ca server
# The ca server will be used to generate self-signed certificates required setting up secured cluster
ca:
  ## If true, enable the nifi-toolkit certificate authority
  enabled: true
  server: "cluster.local"
  service:
    port: 9090
  token: "hfydhd7djdu8rofrmfi9fifyrjrifyfrhbrt6trr4e4dst5sic9"
  admin:
    cn: admin
  serviceAccount:
    create: true
    name: nifi-ca
```

**Logs from the cert-request container**

You can notice two main errors:
- jq: error: Could not open file config.json: No such file or directory
- Service client error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

```
k logs -f nifi-0 -c cert-request


CONNECTED(00000003)
Can't use SSL_get_servername
depth=1 O = cluster.local
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 O = cluster.local
verify return:1
depth=0
verify return:1
DONE
---
Certificate chain
 0 s:
   i:O = cluster.local
 1 s:O = cluster.local
   i:O = cluster.local
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDJDCCAgygAwIBAgIRAOAre8HRXaity+ovwPXE6HUwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMDExMTcyMjIwMjRaFw0yMDEx
MTgyMjIwMjRaMAAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDNRv8Z
kvqOEzYfdE6qSKmc+iBxfpS9fiCHb7ETJnJYFRyrPkxTCZt2IGPu4WrJS0zLXt6k
j7SjPDFnPI+2tcrp3ynp+Ss0ggAuZR4uNQ8XST7k0/nnVTtvBhcCsGNw8qwUQ70T
fEdoosheiuzkESEp7PTb5Lf2ebSzQT+RXA3Np/l/HhazvbqSkDl3B2Lf/HEq+D6T
ExMW51EDxE9oF8wpw1m2cxALFvfcmMiyg9czQIbOhTOAiYPioVRYpmmf8ySXWkSA
FS8hdbYs6lnrpKHh8iTLNW8FirxjG1bg2lPrlPmvGwNG38s6yal0xCufHxTkRONi
NHApLvtV+EZuBEkJAgMBAAGjgYAwfjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwPwYDVR0RAQH/BDUw
M4Yxc3BpZmZlOi8vY2x1c3Rlci5sb2NhbC9ucy9uaWZpLXRlc3Qvc2EvbmlmaS1j
YS1zYTANBgkqhkiG9w0BAQsFAAOCAQEAbdaJOll4aJVo2Iu6j1pfxLKdykF9Nrla
T0i7x6F0OLOMSBnj1jgYMfY/xRCzjjbjSVAXvbvV+O9aJsZjdJp9HdD/Jac6cioL
ddSSRGznIdOCGVRMKEMDJNUwqmp5yRj+mdfRo1K2BfTGuNI8h6SGRzelMf7+WnJp
LVjX3qWmNJZGg5k62DzJMzhRCrIL8khXeAhsNwmzxQoClC1oMNUiy30ea8Czn8Cb
ocPbuqnYLeOuq3arAPp9LKQ8VNgV8asifJlMoFNBLuzvMEqZIF4ASiJa0ySRvggo
cBd8a97tDsJSH/7I9/HO1N9/H6hFO4rwMcOU8AF2cmk3yoYQHeE5vA==
-----END CERTIFICATE-----
subject=

issuer=O = cluster.local

---
Acceptable client certificate CA names
O = cluster.local
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2106 bytes and written 403 bytes
Verification error: self signed certificate in certificate chain
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self signed certificate in certificate chain)
---
2020/11/17 22:21:27 INFO [main] org.apache.nifi.toolkit.tls.service.client.TlsCertificateAuthorityClient: Requesting new certificate from nifi-ca:9090
2020/11/17 22:21:27 INFO [main] org.apache.nifi.toolkit.tls.service.client.TlsCertificateSigningRequestPerformer: Requesting certificate with dn CN=nifi-0.nifi-headless.nifi-test.svc.cluster.local,OU=NIFI from nifi-ca:9090
Service client error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Usage: tls-toolkit service [-h] [args]

Services:
   standalone: Creates certificates and config files for nifi cluster.
   server: Acts as a Certificate Authority that can be used by clients to get Certificates
   client: Generates a private key and gets it signed by the certificate authority.
   status: Checks the status of an HTTPS endpoint by making a GET request using a supplied keystore and truststore.

2020/11/17 22:21:28 INFO [main] org.apache.nifi.toolkit.tls.commandLine.BaseTlsToolkitCommandLine: Command line argument --keyStoreType=PKCS12 only applies to keystore, recommended truststore type of JKS unaffected.
2020/11/17 22:21:29 INFO [main] org.apache.nifi.toolkit.tls.service.client.TlsCertificateAuthorityClient: Requesting new certificate from nifi-ca:9090
2020/11/17 22:21:29 INFO [main] org.apache.nifi.toolkit.tls.service.client.TlsCertificateSigningRequestPerformer: Requesting certificate with dn CN=admin,OU=NIFI from nifi-ca:9090
Service client error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Usage: tls-toolkit service [-h] [args]

Services:
   standalone: Creates certificates and config files for nifi cluster.
   server: Acts as a Certificate Authority that can be used by clients to get Certificates
   client: Generates a private key and gets it signed by the certificate authority.
   status: Checks the status of an HTTPS endpoint by making a GET request using a supplied keystore and truststore.

jq: error: Could not open file config.json: No such file or directory
Can't open keystore.pkcs12 for reading, No such file or directory
140165145389928:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('keystore.pkcs12','rb')
140165145389928:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:
Can't open keystore.pkcs12 for reading, No such file or directory
140618019830632:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('keystore.pkcs12','rb')
140618019830632:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:
```

Questions:
- is it possible to use the `cluster.local` dns name?
- I am missing any configuration?

Thanks
