### ISSUE TITLE
[cetic/nifi] Secure cluster with provided certificates instead of self-signed ones.

### ISSUE THREAD

**Issue by gillhofer** [cetic/helm-nifi#118]
**Is your feature request related to a problem? Please describe.**
Currently, TLS and thus authentification can only be enabled when the provided TLS-toolkit CA is enabled which creates self signed certificates. However, this breaks the browsers trust into the NIFI UI as well as prevents [MiNiFi](https://nifi.apache.org/minifi/) to connect to NIFI because of trust issues. If I understand this right, then this can only be fixed by using either LetsEncrypt (how?) as the CA or some other bought certificates and inject those into the TLS-toolkit CA. However, my technical knowledge about kubernetes / ingress and TLS is limited, hence my description might not be accurate. Please correct me if I'm wrong. 
![image](https://user-images.githubusercontent.com/4135093/105338864-51e7a380-5bdc-11eb-8c22-372e76316535.png)

**Describe the solution you'd like**
I would like to be able to use a given TLS-Certificate for a given Sub-Domain.

**Describe alternatives you've considered**

**Additional context**
There might also be a misunderstanding of the charts `values.yaml`
```yaml
properties:
  # use externalSecure for when inbound SSL is provided by nginx-ingress or other external mechanism
  externalSecure: false
  isNode: true # set to false if ldap is enabled
  httpPort: null # set to null if ldap is enabled
  httpsPort: 9443 # set to 9443 if ldap is enabled
  webProxyHost: XXXX.westeurope.cloudapp.azure.com:9443
  clusterPort: 6007
  clusterSecure: true # set to true if ldap is enabled
  needClientAuth: false

ca:
  ## If true, enable the nifi-toolkit certificate authority
  enabled: true
  persistence:
    enabled: true
  server: XXXX.westeurope.cloudapp.azure.com
  service:
    port: 9090
  token: sixteenCharacters
  admin:
    cn: SOME_CN
  serviceAccount:
    create: false
  openshift:
    scc:
      enabled: false
```
