### ISSUE TITLE
[cetic/nifi] Ingress template incorrectly renders the hosts map: `spec.rules[0].host: Invalid value:  "map[host:subdomain.mydomain.com]"`

### ISSUE THREAD

**Issue by cig0** [cetic/helm-nifi#121]
**Describe the bug**
Hi,

The chart seems to be incorrectly rendering the template when defining a custom host for the ingress. It could also be I'm doing something awfully wrong of course.

**Version of Helm and Kubernetes**:

Helm: `v3.5.2+g167aac7`
API: `v1.16.15-gke.6000`
kubectl: `v1.20.2`

**What happened**:

When I try to deploy the chart with custom values (specifically setting a hostname) I got the following error message:

```bash
helm install --values=values.yaml --namespace=apache-nifi apache-nifi cetic/nifi
Error: Ingress.extensions "apache-nifi-ingress" is invalid: spec.rules[0].host: Invalid value: "map[host:subdomain.mydomain.com]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**What you expected to happen**:

The rendered template should contain:

```yaml
spec:
  rules:
    - host: subdomain.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: apache-nifi
              servicePort: 8080
```

**How to reproduce it** (as minimally and precisely as possible):

Please configure the ingress section in the `values.yaml` file like this:

```yaml
# Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: subdomain.mydomain.com
  path: /
  # If you want to change the default path, see this issue https://github.com/cetic/helm-nifi/issues/22
```

**Anything else we need to know**:

I'm still learning the ropes of the Helm templating system myself.

When checking the rendered template (`helm template . --dry-run`) I see that the relevant section is rendered as follows:

```yaml
spec:
  rules:
    - host: map[host:subdomain.mydomain.com]
      http:
        paths:
          - path: /
            backend:
              serviceName: apache-nifi
              servicePort: 8080
```

Now, when we take a look at the `ingress.yaml` template, the relevant section is defined this way:

```yaml
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- if .Values.properties.clusterSecure}}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
```
