### ISSUE TITLE
nifi oidc issue

### ISSUE THREAD

**Issue by balajir24** [cetic/helm-nifi#135]
Hi Team,

We are trying to implement nifi with oidc setup. 

Getting below error.

`Unable to parse the response from the Token request: Missing JSON object member with key "access_token"`

Below are the values added.

redirect url

```
https://test-nifi.symphony.com/nifi-api/access/oidc/callback
```

in nifi values.yaml file

```
  oidc:
    enabled: true
    discoveryUrl: https://testnifi.b2clogin.com/testnifi.onmicrosoft.com/B2C_1_signin/v2.0/.well-known/openid-configuration
    clientId: <client-id>
    clientSecret: <client-secret>
    claimIdentifyingUser: emails
    additionalScopes: openid, email, profile
```

from Azure, JWT response

```
{
  "exp": 1617885975,
  "nbf": 1617882375,
  "ver": "1.0",
  "iss": "https://siainifi.b2clogin.com/a5a4-429b-a8f5-68ccac297f0e/v2.0/",
  "sub": "055e75ad-cfc1-4312-a3dc-ecf8023f66ea",
  "aud": "b32ee479-a4c7-4666-9af9-efa480399931",
  "nonce": "defaultNonce",
  "iat": 1617882375,
  "auth_time": 1617882375,
  "idp": "https://login.microsoftonline.com/d80d6c58-e5b0-813cb8f8e186/v2.0",
  "emails": [
    "brajendran@gmail.com"
  ],
  "tfp": "B2C_1_signup-test"
}
```

please help on this.
