### ISSUE TITLE
[cetic/nifi] Add option to add annotations to ConfigMap

### ISSUE THREAD

**Issue by angelosanramon** [cetic/helm-nifi#137]
**Is your feature request related to a problem? Please describe.**
I am using ArgoCD to manage my helm deployments. With this helm chart, ArgoCD is failing to create the configMap because of the size of the data. ArgoCD is throwing an error: `The ConfigMap is invalid: metadata.annotations: Too long: must have at most 262144 characters`. ArgoCD provides a workaround by adding the following annotations to the configMap resource:
```
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
```

However, there is no values for adding annotations to the configMap.

**Describe the solution you'd like**
I would like to have an option to add annotations, something like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apache-nifi.fullname" . }}-config
  annotations:
    {{ .Values.configmap.annotations }}
```

**Describe alternatives you've considered**
Clone this helm chart and modify the configMap resource directly. But I would prefer not to do it this way.

**Additional context**
None
