### ISSUE TITLE
[Cetic/Nifi] prometheusMetrics issue

### ISSUE THREAD

**Issue by raefezzeldin** [cetic/helm-nifi#145]
I can't access the metrics of prometheusafter enabling it from grafana , it keeps giving me that error

```
Unknown error during query transaction. Please check JS console logs.
````

![image](https://user-images.githubusercontent.com/1645929/119738160-8f0cbc80-be80-11eb-9dc6-7538bcc6a4d7.png)

**Comment by tunaman** [comment]
While this is definitely not a Nifi issue (Nor a Grafana one for that matter), but at the URL field you should point to your Prometheus url, not nifi metrics. Nifi metrics are collected by Prometheus and thus are available through the Prometheus datasource. After you have correctly configured your prometheus datasource in Grafana you can install a Nifi dashboard for grafana [like this one](https://grafana.com/grafana/dashboards/12314).

**Comment by raefezzeldin** [comment]
@tunaman 

Thanks for your reply, but I can't see Nifi Service in the targets of Promotheus

**Comment by tunaman** [comment]
Without knowing anything about your kubernetes/prometheus setup you should check if all the relevant parts are in place, this means the service for the metrics endpoint is there, you have the servicemonitor correctly configured. I added some configuration below which works for us, hope this helps!

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: nifi
    meta.helm.sh/release-namespace: nifi
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Helm
    chart: nifi-0.6.4
    heritage: Helm
    release: nifi
  name: nifi
  namespace: nifi
spec:
  endpoints:
  - honorLabels: true
    port: metrics
  namespaceSelector:
    matchNames:
    - nifi
  selector:
    matchLabels:
      app: nifi
      release: nifi

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nifi
    meta.helm.sh/release-namespace: nifi
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Helm
    chart: nifi-0.6.4
    heritage: Helm
    release: nifi
  name: nifi-metrics
  namespace: nifi
spec:
  ports:
  - name: metrics
    port: 9092
    protocol: TCP
    targetPort: metrics
  selector:
    app: nifi
    release: nifi
  type: ClusterIP

  Relevant Helm values.yaml configuration

  metrics:
  prometheus:
    enabled: true
    port: 9092
    serviceMonitor:
      enabled: true
      labels: {}
```
