### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by bmgante** [cetic/helm-nifi#154]
Hi,

I am trying to enable ldap authentication for the cluster. 
CA is enabled, ldap parameters configured and pods are running but can´t reach the UI. Is there anything else that must be configured to properly enable ldap authentication?

pods:
```
nifi-0                                             4/4     Running     1          30m
nifi-ca-fc498d866-tdzvn                            1/1     Running     0          67m
nifi-registry-0                                    1/1     Running     0          79m
nifi-zookeeper-0                                   1/1     Running     0          79m
nifi-zookeeper-1                                   1/1     Running     0          79m
nifi-zookeeper-2                                   1/1     Running     0          79m
```

app-log:
`2021-06-25 16:27:01,638 WARN [NiFi Web Server-115] o.a.nifi.web.server.HostHeaderHandler Request host header [nifi.xxx.net:9443] different from web hostname [localhost(:9443)]. Overriding to [localhost:9443/favicon.ico]
`

**Comment by bmgante** [comment]
values.yaml

`properties:
  # use externalSecure for when inbound SSL is provided by nginx-ingress or other external mechanism
  externalSecure: false
  isNode: false # set to false if ldap is enabled
  httpPort: null # set to null if ldap is enabled
  httpsPort: 9443 # set to 9443 if ldap is enabled
  webProxyHost:
  clusterPort: 6007
  clusterSecure: true # set to true if ldap is enabled
  needClientAuth: false
  provenanceStorage: "8 GB"
  siteToSite:
    port: 10000
  authorizer: managed-authorizer
  # use properties.safetyValve to pass explicit 'key: value' pairs that overwrite other configuration
  safetyValve:
    #nifi.variable.registry.properties: "${NIFI_HOME}/example1.properties, ${NIFI_HOME}/example2.properties"
    nifi.web.http.network.interface.default: eth0
    # listen to loopback interface so "kubectl port-forward ..." works
    nifi.web.http.network.interface.lo: lo
`

`
```yaml
# Nifi User Authentication
auth:
  admin: CN=admin, OU=NIFI
  SSL:
    keystorePasswd: env:PASS
    truststorePasswd: env:PASS
  ldap:
    enabled: true
    host: ldaps://truphoneworld.com:636
    searchBase: OU=AADDC Users,DC=truphoneworld,DC=com
    admin: cn=network-voice.homer-app,OU=AADDC Users,DC=truphoneworld,DC=com
    pass: Fgton#12LkdR
    searchFilter: (sAMAccountName=%s)
    userIdentityAttribute: cn
    authStrategy: SIMPLE # How the connection to the LDAP server is authenticated. Possible values are ANONYMOUS, SIMPLE, LDAPS, or START_TLS.
    identityStrategy: USE_DN
    authExpiration: 12 hours
````

**Comment by bmgante** [comment]
This is the error i got when truing to access https url:
![image](https://user-images.githubusercontent.com/27358817/124488450-c6d42180-dda7-11eb-9dca-b42533792d0b.png)

I am wondering if i may have some misconfiguration on values.yml. Does anyone know what could be missing?

**Comment by banzo** [comment]
There are some instructions and examples here: https://github.com/cetic/fadi/blob/develop/doc/USERMANAGEMENT.md#nifi

**Comment by bmgante** [comment]
Even following those instruction I get the same error. Nifi toolkit generates the certificates for this address and I need to reach the ui on the load balancer external address nifi.staging.xxx.net which is defined in lb config below.

From Certificate:
`DNS Name nifi-nifi-0.nifi-nifi-headless.xxx.svc.cluster.local`

Deployed services:
```
kubectl get svc -n xxx --kubeconfig=$HOME/.kube/config-files/xxx.yml | grep nifi
nifi                              LoadBalancer   172.20.52.169    internal-a27ee58c5feb2487e9902a71bec18189-888972753.eu-west-1.elb.amazonaws.com   9443:30236/TCP               11d
nifi-ca                           ClusterIP      172.20.130.19    <none>                                                                            9090/TCP                     4m23s
nifi-headless                     ClusterIP      None             <none>                                                                            9443/TCP,6007/TCP            11d
nifi-metrics                      ClusterIP      172.20.12.155    <none>                                                                            9092/TCP                     10d
nifi-redis                        ClusterIP      172.20.225.208   <none>                                                                            6379/TCP,26379/TCP           10d
nifi-redis-headless               ClusterIP      None             <none>                                                                            6379/TCP,26379/TCP           10d
nifi-registry                     ClusterIP      172.20.108.47    <none>                                                                            80/TCP                       11d
nifi-zookeeper                    ClusterIP      172.20.95.65     <none>                                                                            2181/TCP,2888/TCP,3888/TCP   11d
nifi-zookeeper-headless           ClusterIP      None             <none>                                                                            2181/TCP,2888/TCP,3888/TCP   11d
```

UI service config:
```
service:
  type: LoadBalancer
  httpPort: 8080
  httpsPort: 9443
  nodePort: 30236
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=staging,Function=xxx,Service=nifi
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    #external-dns.alpha.kubernetes.io/hostname: nifi.xxx.net
    external-dns.alpha.kubernetes.io/hostname: nifi.staging.xxx.net
    external-dns.alpha.kubernetes.io/ttl: "60"
```
