### ISSUE TITLE
Load custom nar

### ISSUE THREAD

**Issue by bmgante** [cetic/helm-nifi#156]
I am trying to load a custom NAR using the helm chart and following the indications from readme.
However i have some doubts if after creating this properties and extra volumes how to load the nar itself. Should i manually load it to the container directrory using kubectl or is there any way to store the nar in the project and the chart automatically transfers it to the container when deploying?

```
extraVolumeMounts:
    - name: mycustomlibs
      mountPath: /opt/configuration_resources/custom_lib
  extraVolumes: # this will create the volume from the directory
    - name: mycustomlibs
      hostPath:
        path: "CUSTOM_LIB_FOLDER"
  properties:
    customLibPath: "/opt/configuration_resources/custom_lib"
```

**Comment by bmgante** [comment]
I was able to get the custom processor after transferring the nar to the CUSTOM_LIB_FOLDER i´ve defined for each of cluster nifi container.
However if for some reason pod restarts, the nar does not persists. Is it possible to enable persistence as well for this purpose?

**Comment by bmgante** [comment]
Indeed, not matter of the path i define for CUSTOM_LIB_FOLDER i am only able to get the custom processor available in UI if transferring the nar to the existing extensions directory:

`kubectl -n xxx cp Downloads/nifi-xxx-nar-1.0.9.nar nifi-0:/opt/nifi/nifi-current/extensions -c server  --kubeconfig=$HOME/.kube/config-files/xxx.yml
kubectl -n xxx cp Downloads/nifi-xxx-nar-1.0.9.nar nifi-1:/opt/nifi/nifi-current/extensions -c server  --kubeconfig=$HOME/.kube/config-files/xxx.yml
kubectl -n xxx cp Downloads/nifi-xxx-nar-1.0.9.nar nifi-2:/opt/nifi/nifi-current/extensions -c server  --kubeconfig=$HOME/.kube/config-files/xxx.yml`

After transferring the nar need to full refresh UI page or even open a new session in order to get the nar available in the list of processors.
Does anyone can advise if this is the right procedure to get custom NAR available on nifi helm chart?

**Comment by bmgante** [comment]
My config:
 
```
  extraVolumeMounts:
    - name: mycustomlibs
      mountPath: /opt/configuration_resources/custom_lib
  extraVolumes: # this will create the volume from the directory
    - name: mycustomlibs
      hostPath:
        path: "/opt/nifi/data/custom_lib"
  properties:
    customLibPath: "/opt/configuration_resources/custom_lib"
```
