### ISSUE TITLE
"Unable to validate the access token" even with sticky session enabled

### ISSUE THREAD

**Issue by bmgante** [cetic/helm-nifi#161]
Hi,

I am having from time to time the error:

`Unable to validate the access token.`

After crating the LB i´ve alrady changed the config to enable sticky session:
```
  sessionAffinity: ClientIP

  sessionAffinityConfig:

    clientIP:

      timeoutSeconds: 10800
```

When this happens i need to restart the deployment, accept again the certificate and it will work a few more hours or days... till issues happens again. Seems that for some reason the LB sticky session is not being respected or expires after some time causing the LB to forward the requests to other node of the cluster.

Any idea or workaround?
