### ISSUE TITLE
nifi-registry ingress not working for Kubernetes >= 1.19

### ISSUE THREAD

**Issue by janesenaj** [cetic/helm-nifi#180]
Kube ingress in version >=1.19 has changed its schema from:

```
...
serviceName:
servicePort
...
```

to 

```
...
pathType:
backend:
   service:
      name:
      port:
         number:
...
```
