### ISSUE TITLE
[cetic/nifi] After deployed a new cluster cannot upload a template or or add processors

### ISSUE THREAD

**Issue by erorci** [cetic/helm-nifi#203]
Hi all, 

I need some assistance to try to understand why after deployed a new cluster  whether a I try to upload a template or add processors the nifi returns **Unable to locate group with id "xxxxx-xxxx-xxxxx-xxxxxx"** .

Please let me know which kind of details I can provide that help me to find out a solution for this issue.

Part of my values are :

```
persistence:
  enabled: true #controls most componenents, but not the subcharts (zookeeper, registry)
  storageClass: standard

sts:
  pod:
    annotations:
      security.alpha.kubernetes.io/sysctls: net.ipv4.ip_local_port_range=10000 65000
      prometheus.io/scrape: "true"

metrics:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false

zookeeper:
  persistence:
    enabled: true
    storageClass: "standard"

registry:
  enabled: false
```

Please let me know which kind of details I can provide that help me to find out a solution for this issue.

Thanks,
Emerson
