### ISSUE TITLE
[cetic/nifi] nifi property settings broken if not using LDAP or OIDC

### ISSUE THREAD

**Issue by wknickless** [cetic/helm-nifi#208]
**Describe the bug**

NiFi properties cannot be set unless LDAP or OIDC is turned on.

**Version of Helm, Kubernetes and the Nifi chart**:

First appears in chart version 1.0.2 with pull request #169.

**What you expected to happen**:

Using this values setting:

```
properties:
  safetyValve:
    nifi.content.claim.max.appendable.size: "1 B"
```
...would result in NiFi being configured with that property set.

**What happened**:

The statefulset and (and therefore pods) had no command: stanza whatsoever, so the NiFi property was not set.

**How to reproduce it** (as minimally and precisely as possible):

Use the above values.yaml and observe that the server container in the pods do not have a command: stanza, and that NiFi does not end up configured per that setting.

**Anything else we need to know**:

Commit 0867843cd39d6d1bf4a329969e6956942167589e in templates/statefulset.yaml line 121 disables the command: stanza in the server container.

**Comment by leshibily** [comment]
I have the same issue #211 .

**Comment by wknickless** [comment]
@leshibily I concur that your #211 is a duplicate of this issue.  I've just started work this morning and first on my list is to fix both our issues and provide a pull request.  I'll be sure to mention that here and tag you.

**Comment by leshibily** [comment]
> @leshibily I concur that your #211 is a duplicate of this issue. I've just started work this morning and first on my list is to fix both our issues and provide a pull request. I'll be sure to mention that here and tag you.

Thank you. Appreciate it.

**Comment by wknickless** [comment]
@leshibily A few minutes ago I pushed a series of commits.  The last one was https://github.com/wknickless/helm-nifi/commit/09bc37f12ed3ade380f5893fa3e897c16cd7c5c9 and it restores safetyValve and singleUser to operation.

I don't know if I've broken LDAP or OIDC--or anything else--but at least there are now github actions defined that verify those two things are working.

**Comment by leshibily** [comment]
> @leshibily A few minutes ago I pushed [wknickless@2abc235](https://github.com/wknickless/helm-nifi/commit/2abc235c0e77da265f2a2707ae92b6bc006e0387) which restores safetyValve and singleUser to operation. It also defines some tests to hopefully quickly identify regressions.
> 
> I don't know if I've broken LDAP or OIDC--or anything else--but at least there are now github actions defined that verify those two things are working.

@wknickless I pulled this commit and deployed this in my gke cluster and worked fine. However, when I try to scale nifi replicas to more than 1, I get the following error on the UI.

`Unable to validate the access token.`

See my values.yaml file:

```
# values.yaml
replicaCount: 1
persistence:
    enabled: true
properties:
    isNode: true
    sensitiveKey: "J9rfn9UfdLDODXdR"
    webProxyHost: "nifi.test.example.com"
auth:
    singleUser:
        username: admin
        password: passw0rd456321
zookeeper:
    enabled: false
    url: "confluent-cp-zookeeper-headless.kafka"
registry:
    enabled: false
```

I use an external zookeeper(confluent) and it's deployed within the same cluster.
