### ISSUE TITLE
[cetic/nifi] HTTP is mentioned in the README but appears inconsistently supported

### ISSUE THREAD

**Issue by mnp** [cetic/helm-nifi#226]
**Describe the bug**
The Readme mentions properties.httpPort.  It looks partially supported in the readiness probe for the statefulset, the safety valve, etc.,  but HTTPS is assumed in many places with no branching for HTTP.

The README, values, STS, and Service should probably be clarified and aligned on HTTP.

**Version of Helm, Kubernetes and the Nifi chart**:

1.0.4

**What happened**:

Experimenting setting `properties.httpsPort = null` and `properties.httpPort=8080` as readme implies might work.

**What you expected to happen**:

I was hoping for port 8080 HTTP service to be enabled, and maybe 8443 disabled.

**How to reproduce it** (as minimally and precisely as possible):

     # approx example
     helm install --set properties.httpPort=8080 foo cetic/nifi

**Anything else we need to know**:

**Comment by makapszenna** [comment]
Is it possible to enable HTTP instead of HTTPS? I have problems setting up ingress right now. Thanks for the answers.

**Comment by mnp** [comment]
It /sounds/ like upstream [supports HTTP and HTTPS , but not both at once](https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#security_configuration) but I think someone needs to do the legwork to configure it using this helm. Hopefully a maintainer can confirm.

**Comment by palex351** [comment]
Workaround:

```
properties:
  safetyValve:
    nifi.remote.input.secure: false
    nifi.web.https.port: ""
    nifi.web.http.host: 127.0.0.1
    nifi.web.http.port: 8080
    nifi.security.keystore: ""
    nifi.security.keystoreType: ""
    nifi.security.truststore: ""
    nifi.security.truststoreType: ""
    nifi.security.user.login.identity.provider: ""
    nifi.security.user.authorizer: ""
service:
  processors:
    enabled: true
    ports:
      - name: nifi-http
        port: 8080
        targetPort: 8080
```

**Comment by DekelDevunet** [comment]
Extending your answer, I think the following will work better because there is liveness on the HTTPS port and not on the HTTP one

```
properties:
  safetyValve:
    nifi.remote.input.secure: false
    nifi.web.https.port: ""
    nifi.web.http.host: 0.0.0.0
    nifi.web.http.port: 8443
    nifi.security.keystore: ""
    nifi.security.keystoreType: ""
    nifi.security.truststore: ""
    nifi.security.truststoreType: ""
```
