### ISSUE TITLE
Use external CA instead of nifi-ca

### ISSUE THREAD

**Issue by bmgante** [cetic/helm-nifi#232]
Hi,
Does this helm support to install an external valid certificate (full chain) in a secure cluster instead of having to user nifi-ca which will always throw security warnings on browser?
If yes, would you mind to provide some guidance?

Thanks

**Comment by banzo** [comment]
@bmgante there might be some info on that in #218

**Comment by bmgante** [comment]
Hi @banzo what about generating the certificate externally and just import/install it on NiFi nodes without using nifi-ca? Is it possible?

**Comment by gforeman02** [comment]
@bmgante, this was how I was able to get clustered Nifi working with an external CA.

values.yaml settings:

```
replicaCount: 3

...

secrets:
- name: <your secrets name>
  keys:
    - nifi-0.nifi-headless.<your namespace>.svc.cluster.local.jks
    - nifi-1.nifi-headless.<your namespace>.svc.cluster.local.jks
    - nifi-2.nifi-headless.<your namespace>.svc.cluster.local.jks
    - truststore.jks
    - config.json
    - admin.crt
    - admin.key
  mountPath: /opt/nifi/nifi-current/config-data/certs/
```

Note: The config.json file should have keyStorePassword, keyPassword, and trustStorePassword set.


```
properties:
  isNode: true

...

safetyValve:
  nifi.security.keystoreType: jks
  nifi.security.keystore: ${NIFI_HOME}/config-data/certs/${FQDN}.jks
  nifi.security.keystorePasswd: $(jq -r .keyStorePassword ${NIFI_HOME}/config-data/certs/config.json)
  nifi.security.keyPasswd: $(jq -r .keyPassword ${NIFI_HOME}/config-data/certs/config.json)
  nifi.security.truststoreType: jks
  nifi.security.truststore: ${NIFI_HOME}/config-data/certs/truststore.jks
  nifi.security.truststorePasswd: $(jq -r .trustStorePassword ${NIFI_HOME}/config-data/certs/config.json)
```
