### ISSUE TITLE
[cetic/nifi] Nifi cluster not working 

### ISSUE THREAD

**Issue by shayki5** [cetic/helm-nifi#268]
**Describe the bug**
When I the `replicas` is `1` the nifi is working, I can login ang even connect to the nifi-registry.
When I increased the `replicas` to `2` (or more) I can't login the Nifi UI, got several errors.
I searched all the issues here but without success.
If `ca` is enabled in my values file, I can see this error in the server pod:
```
WARN [Process Cluster Protocol Request-32] o.a.n.c.p.impl.SocketProtocolListener Failed processing protocol message from nifi-1.nifi-headless.data-tools.svc.cluster.local due to Received fatal alert: certificate_unknown
```
or:
```
WARN [Clustering Tasks Thread-1] o.apache.nifi.controller.FlowController Failed to send heartbeat due to: org.apache.nifi.cluster.protocol.ProtocolException: Failed marshalling 'HEARTBEAT' protocol message
```
if `certManager` is enabled, I can see this error in the server pod:
```
Failed to create socket to nifi-0.nifi-headless.data-tools.svc.******.com:6007 due to: java.net.ConnectException: Connection refused (Connection refused)
```
or:
```
Caused by: org.springframework.security.oauth2.jwt.BadJwtException: An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:180)
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.decode(NimbusJwtDecoder.java:137)
        at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.getJwt(JwtAuthenticationProvider.java:97)
```

**Version of Helm, Kubernetes and the Nifi chart**: 
Helm: 13.9.0
K8s: 1.21.7
Nifi chart: 1.1.1

**What happened**:
When I the `replicas` is `1` the nifi is working, I can login ang even connect to the nifi-registry.
When I increased the `replicas` to `2` (or more) I can't login the Nifi UI, got several errors.

**What you expected to happen**:
Can access the Nifi UI.

**How to reproduce it** (as minimally and precisely as possible):
 Increased the `replicas` to `2` (or more)

**Anything else we need to know**:

Here are some information that help troubleshooting:

* if relevant, provide your `values.yaml` or the changes made to the default one (after removing sensitive information)
My `values.yaml` file:
```
---
# Number of nifi nodes
replicaCount: 2

##
image:
  repository: apache/nifi
  tag: "1.16.3"
  pullPolicy: "IfNotPresent"

properties:
  # https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#nifi_sensitive_props_key
  sensitiveKey: test123456789 # Must have at least 12 characters
  isNode: true

auth:
  admin: CN=admin, OU=NIFI
  SSL:
    keystorePasswd: changeMe
    truststorePasswd: changeMe
  
  # Automaticaly disabled if OIDC or LDAP enabled 
  singleUser:
    username: admin
    password: TestingNifi123 # Must to have at least 12 characters

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: true
  # className: nginx
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "localhost:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://localhost:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://nifi.tools.dev.com"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  tls: []
  hosts:
    - nifi.tools.dev.com
  path: /
  # If you want to change the default path, see this issue https://github.com/cetic/helm-nifi/issues/22

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true

# ca server details
# Setting this true would create a nifi-toolkit based ca server
# The ca server will be used to generate self-signed certificates required setting up secured cluster
ca:
  ## If true, enable the nifi-toolkit certificate authority
  enabled: false/true (tried with ca enabled or certManager enabled)
  persistence:
    enabled: true
  server: ""
  service:
    port: 9090
  token: sixteenCharacters
  admin:
    cn: admin
  serviceAccount:
    create: false
    #name: nifi-ca
  openshift:
    scc:
      enabled: false

# cert-manager support
# Setting this true will have cert-manager create a private CA for the cluster
# as well as the certificates for each cluster node.
certManager:
  enabled: false/true (tried with ca enabled or certManager enabled)
  clusterDomain: tools.dev.com
  keystorePasswd: test123
  truststorePasswd: test123
  replaceDefaultTrustStore: false
  additionalDnsNames:
    - localhost
  refreshSeconds: 300
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  # cert-manager takes care of rotating the node certificates, so default
  # their lifetime to 90 days.  But when the CA expires you may need to 
  # 'helm delete' the cluster, delete all the node certificates and secrets, 
  # and then 'helm install' the NiFi cluster again.  If a site-to-site trusted
  # CA or a NiFi Registry CA certificate expires, you'll need to restart all 
  # pods to pick up the new version of the CA certificate.  So default the CA 
  # lifetime to 10 years to avoid that happening very often.
  # c.f. https://github.com/cert-manager/cert-manager/issues/2478#issuecomment-1095545529
  certDuration: 2160h
  caDuration: 87660h

# ------------------------------------------------------------------------------
# Zookeeper:
# ------------------------------------------------------------------------------
zookeeper:
  ## If true, install the Zookeeper chart
  ## ref: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml
  enabled: true
  ## If the Zookeeper Chart is disabled a URL and port are required to connect
  url: ""
  port: 2181
  replicaCount: 3

# ------------------------------------------------------------------------------
# Nifi registry:
# ------------------------------------------------------------------------------
registry:
  ## If true, install the Nifi registry
  enabled: true
  url: ""
  port: 80
  extraEnvs:
  - name: NIFI_REGISTRY_WEB_HTTP_HOST
    value: "0.0.0.0"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: "localhost:18080"
      nginx.ingress.kubernetes.io/proxy-redirect-from: "http://localhost:18080"
      nginx.ingress.kubernetes.io/proxy-redirect-to: "http://nifi-registry.tools.dev.com"
      #kubernetes.io/tls-acme: "true"
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: nifi-registry.tools.dev.com
        paths:
        - "/"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "300m"
  ## Add values for the nifi-registry here
  ## ref: https://github.com/dysnix/charts/blob/master/nifi-registry/values.yaml

```
* the output of the folowing commands:

Check if a pod is in error: 
```bash
kubectl get pod
NAME                  READY   STATUS    RESTARTS   AGE
cert-manager-1662895698-cainjector-85946b945f-x4pxb   1/1     Running   0          26h
cert-manager-1662895698-controller-6849b8f569-l6jmg   1/1     Running   0          26h
cert-manager-1662895698-webhook-6595cb448b-4q8td      1/1     Running   0          26h
nifi-0                                                4/4     Running   0          9m40s
nifi-1                                                4/4     Running   0          9m40s
nifi-ca-65c89cd6b7-pc6bf                              1/1     Running   0          9m40s
nifi-registry-0                                       1/1     Running   0          9m40s
nifi-zookeeper-0                                      1/1     Running   0          9m40s
nifi-zookeeper-1                                      1/1     Running   0          9m40s
nifi-zookeeper-2                                      1/1     Running   0          9m40s
```
I'm not familiar with the cert stuff, I guess it's related somehow, I really appreciate your help.
Thank you!
