### ISSUE TITLE
Can't enable nodePort with https

### ISSUE THREAD

**Issue by oktayalizada** [cetic/helm-nifi#276]
**Describe the bug**
When trying to enable nodeport with https getting like this:
```
replicaCount: 1
image:
   tag: 1.16.3
   pullSecret: regcred
service:
  type: NodePort
```

**Version of Helm, Kubernetes and the Nifi chart**:
nifi: v1.1.2
helm: 3.9.2
kubernetes: 1.2

**What happened**:
All pods are running I can access nifi with port forwarding but when I try to access through nodeport I get:
System Error
```
The request contained an invalid host header [ip:32623] in the request [/nifi/]. Check for request manipulation or third-party intercept.
Valid host headers are [empty] or:

    127.0.0.1
    127.0.0.1:8443
    localhost
    localhost:8443
    [::1]
    [::1]:8443
    nifi-0.nifi-headless.nifi.svc.cluster.local
    nifi-0.nifi-headless.nifi.svc.cluster.local:8443
    nifi.nifi.svc
```

**What you expected to happen**:
I should get nifi main page

**How to reproduce it** (as minimally and precisely as possible):
helm install with the following parameters
```
replicaCount: 1
image:
   tag: 1.16.3
   pullSecret: regcred
service:
  type: NodePort
```
