### ISSUE TITLE
[cetic/nifi] Using subpath for persistence

### ISSUE THREAD

**Issue by timesy** [cetic/helm-nifi#289]
Thank you for your work on the Helm chart, it was really helpful so far!

**Is your feature request related to a problem? Please describe.**
When using persistent storage with this chart, I want to use azurefile-premium (as it is costly with the many reads/writes on azurefile). However this would currently create a 100Gi volume for each directory (logs, config-data, data, ...).

**Describe the solution you'd like**
I would like to be able to set a sub path in order to put these files all on the same volume. I tested it locally by changing `statefulset.yaml` and `values.yaml`:

`values.yaml`

```yaml
persistence:
    enabled: true
    subPath: data
```

`statefulset.yaml` (Just exemplary, would be replaced for every mountPath that has persistence):

```yaml
- name: {{ .Values.persistence.subPath | default "auth-conf" }}
            mountPath: /opt/nifi/nifi-current/auth-conf/
            {{- if and .Values.persistence.enabled .Values.persistence.subPath }}
            subPath: auth-conf
	   {{- end }}

  ...

{{- if and .Values.persistence.enabled .Values.persistence.subPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.persistence.subPath }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and .Values.persistence.enabled (not .Values.persistence.subPath) }}
 (same as before)
{{- end }}
```

**Describe alternatives you've considered**
Maybe I am missing something or there is a better way to reach that goal, however I wasn't able to find something else.
